async page => {
  const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
  const cfg=body=>page.evaluate(body=>fetch('/fixture/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json()),body);
  const fixture=()=>page.evaluate(()=>fetch('/fixture/state').then(r=>r.json()));
  const wait=ms=>page.waitForTimeout(ms);
  const waitKvState=state=>page.waitForFunction(state=>document.getElementById('dashboard').dataset.kvState===state,state);
  const waitAdmin=modes=>page.waitForFunction(async modes=>(await fetch('/fixture/state').then(r=>r.json())).admin.map(x=>x.mode).join(',')===modes,modes);
  const reloadReady=async()=>{await page.reload();await page.waitForFunction(()=>document.getElementById('dashboard').dataset.kvState==='idle'&&!document.getElementById('kvApplyNow').disabled)};
  await cfg({reset:true,admin_delay_ms:180}); await reloadReady();
  await page.locator('#kvBudgetInput').fill('80');
  await page.evaluate(()=>{kvApplyNow.click();kvApplyNow.click()});
  assert(await page.locator('#kvBudgetInput').isDisabled()&&await page.locator('#kvBudgetUnit').isDisabled()&&await page.locator('#kvApplyNow').isDisabled()&&await page.locator('#kvSaveRestart').isDisabled(),'checking did not disable all controls');
  await waitAdmin('dry-run'); await waitKvState('review');
  let s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','review performed more than one dry-run or applied immediately');
  assert(s.admin.every(x=>x.header==='1'),'admin header missing');
  const review=page.locator('#kvReview'); assert(await review.count()===1&&await review.isVisible(),'KV impact review did not open exactly once');
  assert(await review.getAttribute('tabindex')==='-1'&&await review.getAttribute('aria-labelledby')==='kvReviewTitle'&&await page.locator('#dashboard').getAttribute('data-kv-state')==='review','KV review semantics or state marker are missing');
  assert((await review.innerText()).includes('64.0 GB → 80.0 GB')&&(await review.innerText()).includes('需要清理\n否'),'review did not show the budget change and explicit cleanup decision');
  assert(await page.evaluate(()=>document.activeElement===document.getElementById('kvReview')),'review did not receive focus');
  assert(await page.locator('#kvConfirmApply').isVisible()&&await page.locator('#kvCancelApply').isVisible(),'review actions are missing');
  assert(await page.locator('#kvBudgetInput').isDisabled()&&await page.locator('#kvBudgetUnit').isDisabled()&&await page.locator('#kvApplyNow').isDisabled()&&await page.locator('#kvSaveRestart').isDisabled(),'review did not keep all KV controls locked');
  await page.locator('#kvCancelApply').click();
  assert(!(await review.isVisible())&&(await page.locator('#kvBudgetInput').inputValue())==='80','cancel did not hide review or retain target');
  assert(await page.evaluate(()=>document.activeElement===kvApplyNow),'cancel did not restore focus to apply trigger');
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','cancel contacted the server');
  await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click();
  assert(await page.locator('#kvBudgetInput').isDisabled()&&await page.locator('#kvBudgetUnit').isDisabled()&&await page.locator('#kvApplyNow').isDisabled()&&await page.locator('#kvSaveRestart').isDisabled(),'applying did not keep all KV controls locked');
  await waitAdmin('dry-run,dry-run,apply'); await waitKvState('success'); s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run,dry-run,apply','explicit confirmation did not apply the reviewed revision');
  assert((await page.locator('#adminNotice').innerText()).startsWith('运行时：'),'runtime success notice was overwritten');
  assert(!(await page.locator('#kvApplyNow').isDisabled()),'successful apply did not restore controls');

  await cfg({reset:true,admin_delay_ms:180}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80');
  await page.evaluate(()=>{kvApplyNow.click();kvSaveRestart.click()}); await waitAdmin('dry-run'); await waitKvState('review');
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','apply+save was not serialized');
  assert(!(await page.locator('#adminNotice').innerText()).includes('下次启动'),'blocked save overwrote apply notice');
  await cfg({reset:true,admin_delay_ms:180}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80');
  await page.evaluate(()=>{kvSaveRestart.click();kvSaveRestart.click();kvApplyNow.click()});
  assert(await page.locator('#dashboard').getAttribute('data-kv-state')==='saving'&&await page.locator('#kvBudgetInput').isDisabled()&&await page.locator('#kvBudgetUnit').isDisabled()&&await page.locator('#kvApplyNow').isDisabled()&&await page.locator('#kvSaveRestart').isDisabled(),'saving did not lock all KV controls');
  await waitAdmin('persist'); await waitKvState('success'); s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='persist','save double-click or apply interleaved with persistence'); assert(await page.evaluate(()=>document.activeElement===kvSaveRestart),'save success did not restore focus to its trigger');

  await cfg({reset:true,status_delay_ms:1200}); await page.reload(); await wait(3500);
  s=await fixture(); assert(s.status_max===1,'status polling overlapped');

  await cfg({reset:true}); await reloadReady(); await page.locator('#kvBudgetUnit').selectOption('MB'); await page.locator('#kvBudgetInput').fill('255'); await page.locator('#kvApplyNow').click(); await waitKvState('error');
  assert((await page.locator('#adminNotice').innerText()).includes('最小 256 MB'),'small MB validation missing'); s=await fixture(); assert(s.admin.length===0,'invalid MB reached server');
  await page.locator('#kvBudgetInput').fill('256.5'); await page.locator('#kvApplyNow').click(); s=await fixture(); assert(s.admin.length===0,'fractional MB reached server');

  await cfg({reset:true,malformed:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('error'); assert((await page.locator('#adminNotice').innerText()).includes('操作失败'),'malformed response not reported');
  await cfg({reset:true,forbidden:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvSaveRestart').click(); await waitKvState('error'); assert(await page.locator('#kvApplyNow').isDisabled(),'403 did not disable controls');
  await cfg({reset:true}); await reloadReady(); await page.route('**/ds4/admin/kv-cache',route=>route.fulfill({status:403,contentType:'text/plain',body:'forbidden'})); await page.locator('#kvSaveRestart').click(); await waitKvState('error'); assert(await page.locator('#kvApplyNow').isDisabled()&&!await page.locator('#contextSaveRestart').isDisabled()&&(await page.locator('#adminNotice').innerText()).includes('仅可从本机管理'),'non-JSON 403 did not isolate only KV controls'); await page.unroute('**/ds4/admin/kv-cache');

  const rejectRuntime=async(patch,label)=>{await cfg({reset:true,runtime_patch:patch});await reloadReady();await page.locator('#kvBudgetInput').fill('80');await page.locator('#kvApplyNow').click();await waitKvState('error');assert((await page.locator('#adminNotice').innerText()).includes('运行时结果无法读取')&&!(await review.isVisible()),label+' runtime contract was accepted')};
  await rejectRuntime({after_bytes:null},'missing field');
  await rejectRuntime({before_entries:'116'},'wrong numeric type');
  await rejectRuntime({after_bytes:50465865729},'inconsistent after value');
  await rejectRuntime({attempted:false},'unattempted dry-run');
  await rejectRuntime({applied:true},'applied dry-run');
  await rejectRuntime({revision:'bogus'},'unusable revision');
  await cfg({reset:true,apply_runtime_patch:{after_entries:'116'}}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply'); await waitKvState('error'); assert((await page.locator('#adminNotice').innerText()).includes('运行时结果无法读取'),'malformed successful apply runtime was accepted');

  await cfg({reset:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await cfg({offline:true}); await page.waitForFunction(()=>document.getElementById('kvConfirmApply').disabled&&!document.getElementById('kvCancelApply').disabled);
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','offline review changed transaction before confirmation'); await page.evaluate(()=>confirmKvApply()); s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','stale offline review applied'); await page.locator('#kvCancelApply').click(); assert(!(await review.isVisible())&&await page.evaluate(()=>document.activeElement===document.getElementById('kvCapacity')),'offline review cancel did not close and move focus to a safe fallback');
  await cfg({reset:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await cfg({kv:{enabled:false,budget_bytes:68719476736,used_bytes:49392123904,entries:116,revision:'1'}}); await page.waitForFunction(()=>document.getElementById('kvConfirmApply').disabled&&!document.getElementById('kvCancelApply').disabled);
  await page.evaluate(()=>confirmKvApply()); s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run','disabled-cache review applied'); await page.locator('#kvCancelApply').click(); assert(!(await review.isVisible())&&await page.evaluate(()=>document.activeElement===document.getElementById('kvCapacity')),'disabled-cache review cancel did not close and move focus to a safe fallback');

  await cfg({reset:true,mismatch_once:true,mismatch_runtime_patch:{eviction_required:true}}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply,dry-run'); await waitKvState('review');
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run,apply,dry-run'&&(await review.innerText()).includes('需要清理\n是'),'changed eviction flag was auto-applied instead of reviewed');

  await cfg({reset:true,admin_delay_ms:100,mismatch_once:true,mismatch_makes_eviction:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply,dry-run'); await waitKvState('review');
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run,apply,dry-run','changed impact was silently applied');
  assert(s.admin[1].revision==='1','first apply did not echo reviewed revision');
  assert(await review.isVisible()&&(await review.innerText()).includes('90.0 GB')&&(await review.innerText()).includes('需要清理\n是')&&(await review.innerText()).includes('预计清理'),'changed eviction impact was not returned for review');
  assert(await page.evaluate(()=>document.activeElement===document.getElementById('kvReview')),'changed impact review did not receive focus');
  await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply,dry-run,apply'); await waitKvState('success'); s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run,apply,dry-run,apply'&&s.admin[3].revision==='2','second confirmation did not apply revised impact');
  await cfg({reset:true,mismatch_remaining:2}); await reloadReady(); await page.locator('#kvBudgetInput').fill('80'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply,dry-run,apply'); await waitKvState('error');
  assert(/KV 状态持续变化|操作失败/.test(await page.locator('#adminNotice').innerText()),'revision retry cap was not actionable');
  assert(!(await page.locator('#kvApplyNow').isDisabled())&&await page.evaluate(()=>document.activeElement===kvApplyNow),'revision retry cap did not restore controls and focus');
  s=await fixture(); assert(s.admin.map(x=>x.mode).join(',')==='dry-run,apply,dry-run,apply'&&s.admin[1].revision==='1'&&s.admin[3].revision==='2','identical impact did not retry exactly once with the refreshed revision');
  await cfg({reset:true,eviction_fail:true}); await reloadReady(); await page.locator('#kvBudgetInput').fill('32'); await page.locator('#kvApplyNow').click(); await waitKvState('review'); await page.locator('#kvConfirmApply').click(); await waitAdmin('dry-run,apply'); await waitKvState('error');
  assert((await page.locator('#adminNotice').innerText()).includes('操作失败'),'eviction failure notice was not actionable');
  assert(!(await page.locator('#kvBudgetInput').isDisabled())&&!(await page.locator('#kvBudgetUnit').isDisabled())&&!(await page.locator('#kvApplyNow').isDisabled())&&!(await page.locator('#kvSaveRestart').isDisabled()),'500 eviction failure disabled controls');
  s=await fixture(); assert(s.kv.entries===100&&s.kv.used_bytes===(40*2**30)&&s.kv.revision==='2','eviction failure fixture did not publish truthful partial state');
  await page.waitForFunction(()=>document.getElementById('kvUsed').textContent==='40.0 GB'&&document.getElementById('kvEntries').textContent==='100'); assert((await page.locator('#kvUsed').innerText())==='40.0 GB'&&(await page.locator('#kvEntries').innerText())==='100','next status poll did not paint partial-eviction stats');
  await cfg({reset:true}); await page.evaluate(()=>localStorage.setItem('ds4-dashboard-mode','not-a-mode')); await page.reload(); await wait(150);
  assert(await page.locator('#dashboard').getAttribute('data-mode')==='management','management must be the default mode');
  assert(await page.locator('#managementLayout').isVisible(),'management layout must be visible by default');
  assert(await page.locator('#monitorLayout').getAttribute('hidden')===''&&await page.locator('#monitorLayout').getAttribute('aria-hidden')==='true','monitor layout must be hidden by default');
  assert(await page.locator('[data-mode-choice="management"]').getAttribute('aria-pressed')==='true','management mode button must be pressed by default');
  assert(await page.locator('#paperLayout,#terminalLayout,#calmLayout').count()===0,'legacy theme roots must be absent');
  const tokens=await page.evaluate(()=>{const s=getComputedStyle(document.documentElement);return ['paper','surface','ink','muted','line','accent','success','danger'].map(name=>s.getPropertyValue('--'+name).trim())});
  assert(tokens.join(',')==='#f3f0e7,#f8f5ed,#171a1d,#706d65,#c4bfb4,#df4932,#28734b,#a52a1c','precision instrument tokens do not match the approved palette');
  const headings=page.locator('h1'); assert(await headings.count()===2&&await page.locator('h1:visible').count()===1&&(await page.locator('h1:visible').innerText())==='运行与容量','management mode must expose exactly one visible page heading');
  const brand=page.locator('.brand a[href="#managementSummary"]');
  assert(await brand.count()===1&&await brand.locator('[aria-hidden="true"]').count()===1,'brand anchor or status glyph is missing');
  assert(await page.getByRole('navigation',{name:'Dashboard 模式'}).locator('[data-mode-choice]').count()===2,'labeled mode navigation is missing');
  assert(await page.locator('#connectionState>[aria-hidden="true"]').count()===1&&await page.locator('#connectionState>#health').count()===1&&await page.locator('#connectionState>#updatedAt').count()===1,'connection scaffold is incomplete');
  assert(await page.locator('#managementSummary').count()===1,'management summary anchor target is missing');
  await page.evaluate(()=>document.activeElement.blur());
  for (const expected of ['brand','management','monitor']) {
    await page.keyboard.press('Tab');
    const focused=await page.evaluate(()=>{const e=document.activeElement,s=getComputedStyle(e);return {brand:e.matches('.brand a[href="#managementSummary"]'),choice:e.dataset.modeChoice||'',style:s.outlineStyle,width:parseFloat(s.outlineWidth)}});
    assert((expected==='brand'?focused.brand:focused.choice===expected)&&focused.style!=='none'&&focused.width>0,'keyboard focus order or visible outline failed at '+expected);
  }
  await page.locator('#kvBudgetUnit').selectOption('MB'); await page.locator('#kvBudgetInput').fill('255'); await page.locator('#contextNextInput').fill('131071'); await page.locator('#kvApplyNow').click(); await wait(50);
  await page.locator('[data-mode-choice="monitor"]').click();
  assert(await page.locator('#dashboard').getAttribute('data-mode')==='monitor','monitor mode did not apply');
  assert(await page.locator('#managementLayout').getAttribute('hidden')===''&&await page.locator('#managementLayout').getAttribute('aria-hidden')==='true'&&await page.locator('#monitorLayout').getAttribute('hidden')===null&&await page.locator('#monitorLayout').getAttribute('aria-hidden')==='false','mode roots did not switch to monitor');
  assert(await page.locator('h1:visible').count()===1&&(await page.locator('h1:visible').innerText())==='实时运行','monitor mode must expose exactly one visible page heading');
  assert(await page.locator('[data-call-filter]').count()===4&&await page.locator('#callFilterCaller').count()===1,'monitor must own the single four-filter set');
  await page.locator('#callFilterCaller').fill('direct');
  const preserved=await page.evaluate(()=>({kv:document.getElementById('kvBudgetInput').value,unit:document.getElementById('kvBudgetUnit').value,context:document.getElementById('contextNextInput').value,filter:document.getElementById('callFilterCaller').value,notice:document.getElementById('adminNotice').textContent}));
  await wait(1200);
  await page.locator('[data-mode-choice="management"]').click();
  const restored=await page.evaluate(()=>({kv:document.getElementById('kvBudgetInput').value,unit:document.getElementById('kvBudgetUnit').value,context:document.getElementById('contextNextInput').value,filter:document.getElementById('callFilterCaller').value,notice:document.getElementById('adminNotice').textContent}));
  assert(JSON.stringify(restored)===JSON.stringify(preserved)&&preserved.notice.includes('最小 256 MB'),'polling or mode switching reset dirty management targets');
  await page.locator('[data-mode-choice="monitor"]').click();
  await page.reload(); await wait(150);
  assert(await page.locator('#dashboard').getAttribute('data-mode')==='monitor','monitor mode did not persist');
  assert(await page.locator('#monitorLayout').getAttribute('hidden')===null&&await page.locator('#monitorLayout').getAttribute('aria-hidden')==='false','persisted monitor root state is wrong');
  const monitorMetricsText=await page.locator('#monitorMetrics').innerText(); assert(monitorMetricsText.includes('52.7 t/s')&&monitorMetricsText.includes('75.0%')&&monitorMetricsText.includes('解码中 · 运行中')&&monitorMetricsText.includes('hanako-agent'),'monitor metrics are missing decode speed, request KV hit, activity, or service');
  assert(await page.locator('#monitorHost').count()===1,'monitor host section is missing its stable ID');
  assert(await page.locator('#monitorCalls tr[data-request-id]').count()===5,'monitor must show exactly five fixture calls');
  assert((await page.locator('[data-request-id="98"]').innerText()).includes('42.1s')&&(await page.locator('[data-request-id="99"]').innerText()).includes('18.4s'),'finished or active row duration is missing');
  await page.locator('[data-request-id="98"] .request-select').click();
  assert(await page.locator('[data-request-id="98"]').getAttribute('aria-selected')==='true','clicked request was not selected');
  let inspectorText=await page.locator('#requestInspector').innerText(); assert(inspectorText.includes('hermes-agent')&&inspectorText.includes('42.1s')&&inspectorText.includes('61.9%'),'request inspector is missing service, duration, or cache hit');
  await page.locator('[data-request-id="97"] .request-select').focus(); await page.keyboard.press('Enter');
  assert((await page.locator('#requestInspector').innerText()).includes('openclaw')&&await page.evaluate(()=>document.activeElement.closest('[data-request-id]')?.dataset.requestId)==='97','keyboard request selection did not update inspector or preserve row focus');
  await page.locator('#callFilterClient').selectOption('hanako-agent');
  assert((await page.locator('#requestInspector').innerText()).includes('请选择一条调用记录'),'filtering out selection did not reset inspector');
  await page.locator('#callFilterClient').selectOption('<img src=x onerror=alert(1)>');
  const hostileMonitor=page.locator('#monitorCalls'); assert(await hostileMonitor.locator('img,script').count()===0&&(await hostileMonitor.innerText()).includes('<script>坏</script>')&&(await hostileMonitor.innerText()).includes('失败'),'malicious monitor row was parsed as markup or result was not localized');
  await hostileMonitor.locator('.request-select').click(); inspectorText=await page.locator('#requestInspector').innerText(); assert(await page.locator('#requestInspector').locator('img,script').count()===0&&inspectorText.includes('<img src=x onerror=alert(1)>')&&inspectorText.includes('<script>坏</script>'),'malicious inspector values were parsed as markup');
  await page.locator('#callFilterClient').selectOption(''); await page.locator('#callFilterCaller').fill('direct'); await page.locator('#callFilterApi').selectOption('responses'); await page.locator('#callFilterStatus').selectOption('active'); assert((await page.locator('#monitorCalls').innerText()).includes('direct')&&(await page.locator('#monitorCalls').innerText()).includes('进行中'),'monitor caller/API/result filters did not localize active result');
  assert(await page.locator('#requestInspector').getAttribute('tabindex')==='-1','request inspector is not a programmatic focus target');
  await page.setViewportSize({width:1200,height:900}); let monitorResponsive=await page.evaluate(()=>({columns:getComputedStyle(document.querySelector('.monitor-grid')).gridTemplateColumns.trim().split(/\s+/).length,metrics:getComputedStyle(document.querySelector('.monitor-metrics')).gridTemplateColumns.trim().split(/\s+/).length,tableMax:getComputedStyle(document.querySelector('.monitor-table-wrap')).maxHeight})); assert(monitorResponsive.columns===2&&monitorResponsive.metrics===6&&monitorResponsive.tableMax!=='none','wide monitor proportions, metric ruler, or bounded table are missing');
  await page.setViewportSize({width:800,height:900}); monitorResponsive=await page.evaluate(()=>({columns:getComputedStyle(document.querySelector('.monitor-grid')).gridTemplateColumns.trim().split(/\s+/).length,host:getComputedStyle(document.querySelector('.monitor-host .host-ruler')).gridTemplateColumns.trim().split(/\s+/).length})); assert(monitorResponsive.columns===1&&monitorResponsive.host===3,'compact monitor did not stack its main panels or preserve adaptive host metrics');
  await page.setViewportSize({width:390,height:844}); monitorResponsive=await page.evaluate(()=>({w:document.documentElement.scrollWidth,v:innerWidth,metrics:getComputedStyle(document.querySelector('.monitor-metrics')).gridTemplateColumns.trim().split(/\s+/).length,host:getComputedStyle(document.querySelector('.monitor-host .host-ruler')).gridTemplateColumns.trim().split(/\s+/).length,button:document.querySelector('.request-select').getBoundingClientRect().height})); assert(monitorResponsive.w<=monitorResponsive.v&&monitorResponsive.metrics===1&&monitorResponsive.host===1&&monitorResponsive.button>=44,'390px monitor overflows or loses adaptive metrics, host, or touch target sizing'); await page.setViewportSize({width:1200,height:900});
  await page.locator('[data-mode-choice="management"]').click();
  assert(await page.locator('#dashboard').getAttribute('data-mode')==='management','management mode did not reapply');
  assert(await page.locator('#managementLayout').isVisible()&&await page.locator('#monitorLayout').getAttribute('hidden')===''&&await page.locator('#monitorLayout').getAttribute('aria-hidden')==='true','mode roots did not switch back to management');
  assert(await page.locator('h1:visible').count()===1&&(await page.locator('h1:visible').innerText())==='运行与容量','management mode did not restore its sole visible page heading');
  assert(await page.locator('#managementTitle').count()===1&&(await page.locator('#managementTitle').innerText())==='运行与容量','management title is missing');
  assert((await page.locator('#managementPhase').innerText()).includes('解码'),'management phase was not localized');
  assert((await page.locator('#managementContext').innerText()).includes('115,720'),'management context remaining is missing');
  assert((await page.locator('#managementKv').innerText()).includes('46.0 / 64.0 GB'),'management KV summary is missing');
  assert((await page.locator('#kvEffect').innerText()).includes('立即影响运行'),'KV runtime effect is unclear');
  assert((await page.locator('#contextEffect').innerText()).includes('重启后生效'),'context restart effect is unclear');
  assert(await page.locator('#managementRecent table').count()===1&&await page.locator('#managementRecentCalls').getAttribute('aria-live')===null,'management recent calls are not a quiet semantic table');
  assert((await page.locator('#managementRecent thead th').allInnerTexts()).join('/')==='请求/服务/API/结果','management recent call headers are incomplete');
  const managementRecentText=await page.locator('#managementRecentCalls').innerText(); assert(await page.locator('#managementRecentCalls tr[data-call-id]').count()===3&&managementRecentText.includes('hanako-agent')&&managementRecentText.includes('responses'),'management recent calls are incomplete');
  await cfg({call_records:[]}); await wait(1100); assert((await page.locator('#managementRecentCalls').innerText()).includes('暂无调用记录')&&await page.locator('#managementRecentCalls tr').count()===1,'empty management recent calls are not explicit');
  await cfg({call_records:[{request_id:'<img src=x>',client:'<script>坏</script>',api:'<img src=x onerror=alert(1)>',status:'failed',error:''},{request_id:'98',client:'hermes-agent',api:'chat',status:'completed',error:''},{request_id:'97',client:'openclaw',api:'chat',status:'active',error:''}]}); await wait(1100); const hostileRecent=page.locator('#managementRecentCalls'); assert(await hostileRecent.locator('img,script').count()===0&&(await hostileRecent.innerText()).includes('<script>坏</script>')&&(await hostileRecent.innerText()).includes('<img src=x>'),'hostile management recent call text was parsed as markup'); await cfg({reset:true}); await wait(1100);
  assert((await page.locator('#managementHost').innerText()).includes('内存压力'),'management host pressure is missing');
  assert(await page.locator('#dashboard').locator('#contextSaveRestart,#kvApplyNow,#kvSaveRestart').count()===3,'shared administration controls disappeared');
  const forbidden=['Counters reset when','Token hit rate','Request hit rate','Outcomes','Used','Budget','Entries / utilization','Disk KV capacity','Current request','tokens per second'];
  const desktop=await page.evaluate(()=>({w:document.documentElement.scrollWidth,v:innerWidth,text:document.body.innerText})); assert(desktop.w<=desktop.v&&desktop.text.includes('管理模式')&&desktop.text.includes('上下文窗口')&&desktop.text.includes('运行与容量')&&forbidden.every(s=>!desktop.text.includes(s)),'desktop layout or Chinese labels missing');
  await page.setViewportSize({width:800,height:900}); await wait(50); const compact=await page.evaluate(()=>({nav:getComputedStyle(document.querySelector('.management-nav')).display,management:getComputedStyle(document.querySelector('.management-grid')).gridTemplateColumns,settings:getComputedStyle(document.querySelector('.settings-grid')).gridTemplateColumns})); assert(compact.nav==='none'&&!compact.management.includes('180px')&&compact.settings.trim().split(/\s+/).length===2,'compact management breakpoint did not hide the sidebar while preserving two setting columns');
  await page.setViewportSize({width:390,height:844}); await wait(50); const mobile=await page.evaluate(()=>({w:document.documentElement.scrollWidth,v:innerWidth,text:document.body.innerText,settings:getComputedStyle(document.querySelector('.settings-grid')).gridTemplateColumns})); assert(mobile.w<=mobile.v&&mobile.settings.trim().split(/\s+/).length===1&&forbidden.every(s=>!mobile.text.includes(s)),'mobile dashboard overflows, keeps two setting columns, or exposes English labels'); await page.setViewportSize({width:1440,height:900});
  assert((await page.locator('#contextNextInput').getAttribute('min'))==='4096','context input minimum does not match server');
  await page.locator('#contextNextInput').fill('4095'); await page.locator('#contextSaveRestart').click(); await wait(50); s=await fixture(); assert(s.context_admin.length===0,'below-minimum context reached server'); assert((await page.locator('#contextNotice').innerText()).includes('4,096 到 2,147,483,647')&&await page.locator('#contextNotice').evaluate(e=>e.className==='notice bad'),'invalid context did not show actionable Chinese error'); await page.evaluate(()=>document.activeElement.blur()); await wait(1100); assert((await page.locator('#contextNextInput').inputValue())==='4095','polling replaced a dirty context target after validation failure');
  await page.locator('#contextNextInput').fill('2147483648'); await page.locator('#contextSaveRestart').click(); await wait(50); s=await fixture(); assert(s.context_admin.length===0,'above-maximum context reached server');
  await page.locator('#contextNextInput').fill('131072'); await page.locator('#contextSaveRestart').click(); await wait(1100); s=await fixture(); assert(s.context_admin[0].header==='1'&&s.context_admin[0].value===131072,'context admin header or payload missing'); const contextSaved=await page.locator('#contextNotice').innerText(); assert(contextSaved.includes('需要重启')&&contextSaved.includes('当前运行值未改变'),'context restart copy missing'); assert((await page.locator('#contextNextInput').inputValue())==='131072','polling replaced saved next-start context limit with live limit');
  await cfg({reset:true,context_fail_once:true}); await page.reload(); await wait(100); await page.locator('#contextNextInput').fill('131072'); await page.locator('#contextSaveRestart').click(); await wait(50); assert((await page.locator('#contextNotice').innerText()).includes('上下文设置失败，请检查数值后重试。')&&await page.locator('#contextNotice').evaluate(e=>e.className==='notice bad'),'context failure was not localized or marked bad'); await page.locator('#contextSaveRestart').click(); await wait(50); s=await fixture(); const contextRetried=await page.locator('#contextNotice').innerText(); assert(s.context_admin.length===2&&contextRetried.includes('需要重启')&&contextRetried.includes('当前运行值未改变')&&await page.locator('#contextNotice').evaluate(e=>e.className==='notice'),'context success retry did not clear error notice');
  await cfg({reset:true,context_forbidden:true}); await page.reload(); await wait(100); await page.locator('#contextSaveRestart').click(); await wait(50); assert(await page.locator('#contextSaveRestart').isDisabled()&&!await page.locator('#kvApplyNow').isDisabled(),'context 403 did not isolate controls');
  await cfg({reset:true,context_durable:false}); await page.reload(); await wait(100); await page.locator('#contextSaveRestart').click(); await wait(50); assert((await page.locator('#contextNotice').innerText()).includes('已提交，但尚未确认已持久化'),'context durable failure was not truthful');
  await cfg({reset:true,host_available:false}); await page.reload(); await wait(100); assert((await page.locator('#managementHostPhysical').innerText())==='不可用'&&(await page.locator('#managementHostPressure').innerText())==='不可用'&&(await page.locator('#managementHostRss').innerText())==='不可用'&&(await page.locator('#monitorHostPhysical').innerText())==='不可用'&&(await page.locator('#monitorHostPressure').innerText())==='不可用'&&(await page.locator('#monitorHostRss').innerText())==='不可用','unknown host was not explicit in both modes'); await cfg({offline:true}); await wait(1150); assert((await page.locator('#health').innerText())==='数据已过期','offline snapshot was not marked stale');
  await page.screenshot({path:'output/playwright/dashboard-management-desktop.png',fullPage:true});
  return {ok:true,double_apply:'one transaction',apply_save:'one transaction',poll_max_active:1,revision_sequence:s.admin.map(x=>x.mode)};
}
